export const font_styles = [
  {
    text: "classic",
    font_family: "'Black Ops One', system-ui",
    font_name: "Black Ops One",
    font_size: 32,
    color: "#597cff",
    bold: "normal",
    italic: "normal",
    underline: "none",
    text_align: "center",
    text_outline: "", // webkit_text_stroke
    text_shadow: "",
  },
  {
    text: "SALE",
    font_family: "'Staatliches', sans-serif",
    font_name: "Staatliches",
    font_size: 52,
    color: "white",
    bold: "normal",
    italic: "normal",
    underline: "none",
    text_align: "center",
    text_outline: "1px pink",
    text_shadow: "4px 4px 0 #b64648, 8px 8px 0 #713d3f",
  },
  {
    text: "LIMITED",
    font_family: "'Archivo Black', sans-serif",
    font_name: "Archivo Black",
    font_size: 28,
    color: "transparent",
    bold: "normal",
    italic: "normal",
    underline: "none",
    text_align: "center",
    text_outline: "1px orangered",
    text_shadow: "",
  },
  {
    text: "ESCAPE",
    font_family: "'Slackey', sans-serif",
    font_name: "Slackey",
    font_size: 28,
    color: "silver",
    bold: "normal",
    italic: "normal",
    underline: "none",
    text_align: "center",
    text_outline: "",
    text_shadow: "",
  },
  {
    text: "TATTOO",
    font_family: "'Danfo', serif",
    font_name: "Danfo",
    font_size: 32,
    color: "#df964a",
    bold: "normal",
    italic: "normal",
    underline: "none",
    text_align: "center",
    text_outline: "",
    text_shadow: "",
  },
  {
    text: "GLOW",
    font_family: "'Nova Mono', monospace",
    font_name: "Nova Mono",
    font_size: 42,
    color: "rgb(81 244 4)",
    bold: "normal",
    italic: "normal",
    underline: "none",
    text_align: "center",
    text_outline: "",
    text_shadow: "0 0 10px #a9fe81,0 0 15px #a9fe81",
  },
  {
    text: "LARGE",
    font_family: "'Monoton', sans-serif",
    font_name: "Monoton",
    font_size: 32,
    color: "white",
    bold: "normal",
    italic: "normal",
    underline: "none",
    text_align: "center",
    text_outline: "",
    text_shadow: "",
  },
  {
    text: "glitch",
    font_family: "'Playwrite AR', cursive",
    font_name: "Playwrite AR",
    font_size: 32,
    color: "white",
    bold: "normal",
    italic: "normal",
    underline: "none",
    text_align: "center",
    text_outline: "",
    text_shadow: "3px 3px 0 red, -3px -3px 0 skyblue",
  },
  {
    text: "BRUNCH",
    font_family: "'Rubik Distressed', system-ui",
    font_name: "Rubik Distressed",
    font_size: 28,
    color: "#ffd200",
    bold: "normal",
    italic: "normal",
    underline: "none",
    text_align: "center",
    text_outline: "",
    text_shadow: "0px 4px 0 #fb4f54",
  },
  {
    text: "PIZZA",
    font_family: "'Wendy One', sans-serif",
    font_name: "Wendy One",
    font_size: 36,
    color: "#09b3e4",
    bold: "normal",
    italic: "normal",
    underline: "none",
    text_align: "center",
    text_outline: "",
    text_shadow: "",
  },
];
